### ISSUE TITLE
Deriving initial secrets QUIC-TLS

### ISSUE THREAD

**Issue by WillemvdKletersteeg** [futoin/util-js-hkdf#16]
I am trying to implement a QUIC packet parser. QUIC uses "header protection" in the form of a mask that is derived using HKDF, using a specified salt (as per RFC spec) and the destination connection ID (which is in the packet header).

The RFC (9001: https://www.rfc-editor.org/rfc/rfc9001.html#name-keys) has a small example of this key derivation in the Appendices, Appendix 1.A. I'm trying to derive the initial secrets using the data specified in this appendix. I am able to derive the PRK correctly (the RFC calls it the "initial_secret"), but somehow I am unable to expand the other secrets correctly. I do get an output, but not correct output.

My code:
```
const salt_v1 = Buffer.from('38762cf7f55934b34d179ae6a4c80cadccbb7f0a', 'hex');      
const test_dcid = Buffer.from('8394c8f03e515708', 'hex');

const prk = hkdf.extract('sha256', 32, test_dcid, salt_v1);

const client_initial_secret = hkdf.expand('sha256', 32, prk, 32, "tls13 client in");
const server_initital_secret = hkdf.expand('sha256', 32, prk, 32, "tls13 server in");

const client_key = hkdf.expand('sha256', 32, client_initial_secret, 16, "tls13 quic key");
const client_iv = hkdf.expand('sha256', 32, client_initial_secret, 12, "tls13 quic iv");
const client_hp = hkdf.expand('sha256', 32, client_initial_secret, 16, "tls13 quic hp");

const server_key = hkdf.expand('sha256', 32, server_initital_secret, 16, "tls13 quic key");
const server_iv = hkdf.expand('sha256', 32, server_initital_secret, 12, "tls13 quic iv");
const server_hp = hkdf.expand('sha256', 32, server_initital_secret, 16, "tls13 quic hp");
```

The prk is 7db5df06e7a69e432496adedb00851923595221596ae2ae9fb8115c1e9ed0a44 after the hkdf.extract(), which is correct according to the spec. But what am I doing wrong with the hkdf.expand|() functions? I have tried every combination of inputs, lengths, etc. and I'm running out of options. Any help would be greatly appreciated.

**Comment by andvgal** [comment]
Well, according to [RFC8446: section 7.1 Key Schedule](https://datatracker.ietf.org/doc/html/rfc8446#section-7.1), there is HKDF extension called "HKDF-Expand-Label" and the label has quite specific format.

I'll get to this a bit later today.

**Comment by WillemvdKletersteeg** [comment]
> Well, according to [RFC8446: section 7.1 Key Schedule](https://datatracker.ietf.org/doc/html/rfc8446#section-7.1), there is HKDF extension called "HKDF-Expand-Label" and the label has quite specific format.
> 
> I'll get to this a bit later today.

Yes, I've seen that RFC as well. That's why I added the "tls 13 " to the labels, which is not in the QUIC (QUIC-TLS) specifications. I also found this in other implementations of QUIC. But the pseudode in that RFC did not make much sense to me... 

Thank you for looking into it. Very much appreciated!

**Comment by andvgal** [comment]
Yes, it's not just about 'tls13 ' prefix. There is quite specific coding of the label which include big-endian target length and length-prefixed encoding of variable-length vectors.

Please use v1.4.0 with new `futoin-hkdf/tls` sub-module. You can also check the unit test update specially for this case: https://github.com/futoin/util-js-hkdf/blob/master/test/unittest.js#L260

**Comment by andvgal** [comment]
v1.4.1 has a minor bug fix, for a last-minute change and missing unittest

**Comment by WillemvdKletersteeg** [comment]
Will do! Thanks a lot!
