### ISSUE TITLE
TLS subpackage not installed with "npm install"

### ISSUE THREAD

**Issue by WillemvdKletersteeg** [futoin/util-js-hkdf#17]
I have just updated futoin-hkdf to 1.4.1 to include the new TLS functions but the installed package does not come with tls.js. I have to manually copy it from the repo.

**Comment by andvgal** [comment]
Fixed in v1.4.2, sorry about that.

**Comment by WillemvdKletersteeg** [comment]
No problem at all, thank you. I'm a happy camper, the HKDF-Expand-Label works flawlessly!
