### ISSUE TITLE
missing TypeScript declaration file

### ISSUE THREAD

**Issue by okuryu** [futoin/util-js-hkdf#3]
Would you mind making a declaration file for TypeScript? I couldn't find them.

**Comment by andvgal** [comment]
@okuryu please feel to contribute. I, personally, do not use TypeScript and it would be difficult for me to assess my own solution.

**Comment by okuryu** [comment]
yup, I take a look.

**Comment by okuryu** [comment]
okay, I just created a patch. https://github.com/futoin/util-js-hkdf/pull/4

**Comment by andvgal** [comment]
@okuryu thank you very much for your contribution!

You can find a new release v1.2.0 with your changes: https://www.npmjs.com/package/futoin-hkdf

**Comment by okuryu** [comment]
Thanks!
